# Generated by Django 5.1.4 on 2024-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_daily_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="notification_preferences",
            field=models.JSONField(
                blank=True, default=dict, help_text="User notification preferences"
            ),
        ),
    ]
