# Generated by Django 5.1.4 on 2024-12-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_notification_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_reminder',
        ),
    ]
