# Generated by Django 5.1.4 on 2024-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="target_completions",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of times to complete this habit"
            ),
        ),
    ]
